image: continuumio/miniconda3

before_script:
  - conda config --add channels conda-forge
  - conda install -c conda-forge mamba
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda clean -a -y
  - conda clean --tarballs -y
  - mamba install snakemake click==7.0 rpy2

stages:
    - linting
    - rulegraph
    - run
    - nohostfiltering
    - cat
    
# DAG
rulegraph:
  stage: rulegraph
  script: 
    - cp config.sample.json config.json
    - snakemake --rulegraph --use-conda

nohostfiltering:
  stage: nohostfiltering
  script:
    - cp config.sample.no-host-filtering.json config.json
    - snakemake --rulegraph --use-conda
    - snakemake -n
cat:
  stage: cat
  script:
    - snakemake --configfile config.sample.json -j 8 --use-conda --until CAT_summarize 

run:
  stage: run
  script:
    - cp config.sample.json config.json
    - snakemake -n
    - snakemake  --use-conda -j 8
    
linting:
  stage: linting
  script:
    - snakemake --lint --configfile config.sample.json
    - snakemake --use-conda --conda-create-envs-only --conda-frontend mamba -j 8
    - snakemake --use-conda --conda-frontend mamba -j 8
